### ISSUE TITLE
Source data from LTER website

### ISSUE THREAD

**Issue by limnoliver** [limnoliver/CSI-Nutrient-Time-Series#2]
Source nutrient data from LTER website for HLM models and geo data for RF analysis.

**Comment by jsta** [comment]
Seems like this has been done in d64c6b406715b86609813487426e6803d7dec4f6? What is the landing page url for this data? We should make sure this is included in the `LAGOS` package!

**Comment by limnoliver** [comment]
Oh yes, forgot to close! The data are on the [LTER portal ](https://portal.lternet.edu/nis/mapbrowse?packageid=knb-lter-ntl.333.3). I'll work on incorporating these (and other LAGOS published products) in the `LAGOS` package.
